#!/bin/sh

set -e

CDPATH="" cd -- "$(dirname -- "$(dirname -- "$0")")"

make -s bin/semver-next bin/octo bin/goreleaser

GITHUB_SHA="${GITHUB_SHA:-"$(git rev-parse HEAD)"}"
GITHUB_REPOSITORY="${GITHUB_REPOSITORY:-"WillAbides/semver-next"}"

bin/semver-next "$GITHUB_REPOSITORY" -r "$GITHUB_SHA" --create-tag

git fetch --tags

bin/goreleaser release
